/**
 * Demo content fallbacks — used when the backend returns empty arrays
 * so the landing page is never visually empty.
 */
import type { ContentItem } from "@/types/api";

const img = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1400&q=80`;
const avatar = (seed: string) =>
  `https://api.dicebear.com/9.x/initials/svg?seed=${encodeURIComponent(seed)}&backgroundColor=2563eb,7c3aed,db2777,16a34a,f59e0b`;

const HLS = "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8";

export const DEMO_CONTENT: ContentItem[] = [
  {
    id: "demo-1",
    title: "Champions League Final — Live from Wembley",
    subtitle: "Sports",
    description: "Goals, drama and trophy lift. Don't miss a single moment.",
    thumbnailUrl: img("photo-1551958219-acbc608c6377"),
    streamUrl: HLS,
    categoryId: "sports",
    categorySlug: "sports",
    host: { id: "h1", name: "SkySports HQ", avatarUrl: avatar("SkySports") },
    viewerCount: 184230,
    isLive: true,
    isFeatured: true,
    tags: ["football", "uefa", "final"],
  },
  {
    id: "demo-2",
    title: "NBA Playoffs Watch Party 🏀",
    subtitle: "Sports",
    description: "Live reactions to game 7 with the squad.",
    thumbnailUrl: img("photo-1546519638-68e109498ffc"),
    streamUrl: HLS,
    categoryId: "sports",
    categorySlug: "sports",
    host: { id: "h2", name: "Court Vision", avatarUrl: avatar("Court Vision") },
    viewerCount: 42180,
    isLive: true,
    isFeatured: true,
    tags: ["nba", "basketball"],
  },
  {
    id: "demo-3",
    title: "Valorant Ranked Grind — Radiant Push",
    subtitle: "Gaming",
    description: "Climbing solo queue with the new agent.",
    thumbnailUrl: img("photo-1542751371-adc38448a05e"),
    streamUrl: HLS,
    categoryId: "gaming",
    categorySlug: "gaming",
    host: { id: "h3", name: "NovaPlays", avatarUrl: avatar("NovaPlays") },
    viewerCount: 12840,
    isLive: true,
    isFeatured: true,
    tags: ["valorant", "fps"],
  },
  {
    id: "demo-4",
    title: "Late Night Lo-Fi Beats 🎧",
    subtitle: "Music",
    description: "Chill mixes for studying & coding.",
    thumbnailUrl: img("photo-1511671782779-c97d3d27a1d4"),
    streamUrl: HLS,
    categoryId: "music",
    categorySlug: "music",
    host: { id: "h4", name: "MidnightFM", avatarUrl: avatar("MidnightFM") },
    viewerCount: 8920,
    isLive: true,
    tags: ["lofi", "chill"],
  },
  {
    id: "demo-5",
    title: "Street Food Tour — Bangkok 🌶️",
    subtitle: "Food",
    description: "Pad thai, mango sticky rice and more!",
    thumbnailUrl: img("photo-1504674900247-0877df9cc836"),
    streamUrl: HLS,
    categoryId: "food",
    categorySlug: "food",
    host: { id: "h5", name: "TasteTrails", avatarUrl: avatar("TasteTrails") },
    viewerCount: 5430,
    isLive: true,
    tags: ["food", "travel"],
  },
  {
    id: "demo-6",
    title: "Paris Fashion Week — Front Row",
    subtitle: "Fashion",
    description: "Backstage access from the runway.",
    thumbnailUrl: img("photo-1469334031218-e382a71b716b"),
    streamUrl: HLS,
    categoryId: "fashion",
    categorySlug: "fashion",
    host: { id: "h6", name: "Atelier Live", avatarUrl: avatar("Atelier Live") },
    viewerCount: 17320,
    isLive: true,
    isFeatured: true,
    tags: ["fashion", "runway"],
  },
  {
    id: "demo-7",
    title: "Tech Talk: Building at the Edge",
    subtitle: "Podcasts",
    description: "Deep-dive interview with founders shipping AI products.",
    thumbnailUrl: img("photo-1485579149621-3123dd979885"),
    streamUrl: HLS,
    categoryId: "podcasts",
    categorySlug: "podcasts",
    host: { id: "h7", name: "DevCast", avatarUrl: avatar("DevCast") },
    viewerCount: 3210,
    isLive: true,
    tags: ["podcast", "tech"],
  },
  {
    id: "demo-8",
    title: "Sunrise Yoga Flow 🧘",
    subtitle: "Lifestyle",
    description: "Start your day grounded and energized.",
    thumbnailUrl: img("photo-1545205597-3d9d02c29597"),
    streamUrl: HLS,
    categoryId: "lifestyle",
    categorySlug: "lifestyle",
    host: { id: "h8", name: "MorningGlow", avatarUrl: avatar("MorningGlow") },
    viewerCount: 2140,
    isLive: true,
    tags: ["yoga", "wellness"],
  },
];

export const DEMO_FEATURED: ContentItem[] = DEMO_CONTENT.filter(
  (c) => c.isFeatured,
);
